import { library, config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'

import {
  faPaw,
  faSyringe,
  faScissors,
  faStore,
  faStethoscope,
  faCalendarDays,
  faUsers,
  faChartLine,
  faCashRegister,
  faBoxesStacked,
  faFileInvoiceDollar,
  faBell,
  faGear,
  faShieldHalved,
  faHeadset,
  faRocket,
  faMobileScreenButton,
  faQrcode,
  faWheatAwn,
  faBone,
  faCat,
  faDog,
  faHeart,
  faCheck,
  faXmark,
  faChevronDown,
  faChevronRight,
  faArrowRight,
  faBars,
  faMagnifyingGlass,
  faEnvelope,
  faPhone,
  faLocationDot,
  faStar,
  faCircleCheck,
  faPlay,
  faSpinner,
  faClock,
  faUser,
  faRightFromBracket,
  faHouse,
  faFileMedical,
  faVial,
  faPrescriptionBottleMedical,
  faCamera,
  faImages,
  faRoute,
  faTags,
  faTruck,
  faCartShopping,
  faComments,
  faGlobe,
} from '@fortawesome/free-solid-svg-icons'

import {
  faCalendar as faCalendarRegular,
  faCreditCard as faCreditCardRegular,
  faCircleQuestion as faCircleQuestionRegular,
  faEye as faEyeRegular,
} from '@fortawesome/free-regular-svg-icons'

import {
  faWhatsapp,
  faInstagram,
  faFacebook,
  faTwitter,
} from '@fortawesome/free-brands-svg-icons'

// Prevent fontawesome from adding its CSS since we did it manually above
config.autoAddCss = false

// Add icons to the library so you can use them globally
library.add(
  // Solid icons
  faPaw,
  faSyringe,
  faScissors,
  faStore,
  faStethoscope,
  faCalendarDays,
  faUsers,
  faChartLine,
  faCashRegister,
  faBoxesStacked,
  faFileInvoiceDollar,
  faBell,
  faGear,
  faShieldHalved,
  faHeadset,
  faRocket,
  faMobileScreenButton,
  faQrcode,
  faWheatAwn,
  faBone,
  faCat,
  faDog,
  faHeart,
  faCheck,
  faXmark,
  faChevronDown,
  faChevronRight,
  faArrowRight,
  faBars,
  faMagnifyingGlass,
  faEnvelope,
  faPhone,
  faLocationDot,
  faStar,
  faCircleCheck,
  faPlay,
  faSpinner,
  faClock,
  faUser,
  faRightFromBracket,
  faHouse,
  faFileMedical,
  faVial,
  faPrescriptionBottleMedical,
  faCamera,
  faImages,
  faRoute,
  faTags,
  faTruck,
  faCartShopping,
  faComments,
  faGlobe,
  // Regular icons
  faCalendarRegular,
  faCreditCardRegular,
  faCircleQuestionRegular,
  faEyeRegular,
  // Brand icons
  faWhatsapp,
  faInstagram,
  faFacebook,
  faTwitter,
)
